// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS_AXuOxco4Pg7DMq4seubA0JQwXsvUgM',
    appId: '1:714409329329:web:b6e6f985fc6d41cfd6d890',
    messagingSenderId: '714409329329',
    projectId: 'assesment-14010',
    authDomain: 'assesment-14010.firebaseapp.com',
    storageBucket: 'assesment-14010.firebasestorage.app',
    measurementId: 'G-418V5MCZXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXilqUbs3QGBtyMivsDKoBHRgyMSZmRrQ',
    appId: '1:714409329329:android:34411faf1b475539d6d890',
    messagingSenderId: '714409329329',
    projectId: 'assesment-14010',
    storageBucket: 'assesment-14010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbrCDgkSHvR63paaF5g-K8NvzhwBnTDko',
    appId: '1:714409329329:ios:e9180aa92cdced77d6d890',
    messagingSenderId: '714409329329',
    projectId: 'assesment-14010',
    storageBucket: 'assesment-14010.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbrCDgkSHvR63paaF5g-K8NvzhwBnTDko',
    appId: '1:714409329329:ios:e9180aa92cdced77d6d890',
    messagingSenderId: '714409329329',
    projectId: 'assesment-14010',
    storageBucket: 'assesment-14010.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS_AXuOxco4Pg7DMq4seubA0JQwXsvUgM',
    appId: '1:714409329329:web:eafe67e96796689dd6d890',
    messagingSenderId: '714409329329',
    projectId: 'assesment-14010',
    authDomain: 'assesment-14010.firebaseapp.com',
    storageBucket: 'assesment-14010.firebasestorage.app',
    measurementId: 'G-BEBC462X0B',
  );
}
